# MINIMAL secrets.toml - Just to get the app running
# Add this to Streamlit Cloud Secrets

[app]
domain = "https://example.com/"
max_concurrency = 3

# Dummy GSC config (app will run but GSC API won't work)
[gsc]
type = "service_account"
project_id = "dummy"
private_key_id = "dummy"
private_key = """-----BEGIN PRIVATE KEY-----
dummy
-----END PRIVATE KEY-----"""
client_email = "dummy@dummy.iam.gserviceaccount.com"
client_id = "123"
token_uri = "https://oauth2.googleapis.com/token"

# Leave DataForSEO empty
[dataforseo]
login = ""
password = ""

# Leave Sheets empty
[sheets]
type = "service_account"
project_id = ""
private_key_id = ""
private_key = ""
client_email = ""
client_id = ""
token_uri = ""

# Add your OpenAI key here (GET FROM: https://platform.openai.com/api-keys)
[openai]
api_key = "sk-proj-YOUR-ACTUAL-OPENAI-KEY-HERE"  # REQUIRED for AI features
default_models = ["gpt-4o-mini"]

# Leave these empty if not using
[anthropic]
api_key = ""
default_models = []

[gemini]
api_key = ""
default_models = []
