# Copy this to .streamlit/secrets.toml and fill your values

[gsc]
# Service Account JSON for Search Console API
type = "service_account"
project_id = ""
private_key_id = ""
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = ""
client_id = ""
token_uri = "https://oauth2.googleapis.com/token"

[dataforseo]
login = ""
password = ""
default_location = "US"
default_language = "English"

[sheets]
# Separate Service Account JSON with Google Sheets/Drive access
type = "service_account"
project_id = ""
private_key_id = ""
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = ""
client_id = ""
token_uri = "https://oauth2.googleapis.com/token"

[openai]
api_key = ""
default_models = ["gpt-4o-mini", "gpt-4o", "gpt-4.1-mini"]

[anthropic]
api_key = ""
default_models = ["claude-3-haiku-20240307", "claude-3-sonnet-20240229"]

[gemini]
api_key = ""
default_models = ["gemini-1.5-flash", "gemini-1.5-pro"]

[app]
domain = "https://www.example.com/"
max_concurrency = 3
